create table KURZUS (
 kod integer GENERATED BY DEFAULT AS IDENTITY,
 nev VARCHAR(255) NOT NULL,
 max_letszam integer not null,
 oktato_kod integer,
 terem_kod integer,
 epulet_kod integer,
 primary key(kod)
);

create table EPULET (
 kod integer GENERATED BY DEFAULT AS IDENTITY,
 nev VARCHAR(255) NOT NULL,
 primary key(kod)
);

create table FELHASZNALO (
 kod integer GENERATED BY DEFAULT AS IDENTITY,
 jelszo VARCHAR(255) NOT NULL,
 keresztnev VARCHAR(255) NOT NULL,
 vezeteknev VARCHAR(255) NOT NULL,
 admin NUMBER(1) not null,
 primary key(kod)
);

create table TEREM (
 kod integer GENERATED BY DEFAULT AS IDENTITY,
 nev VARCHAR(255) NOT NULL,
 epulet_kod integer,
 FOREIGN KEY(epulet_kod) REFERENCES EPULET(kod),
 primary key(kod)
);

create table LOG (
 kod integer GENERATED BY DEFAULT AS IDENTITY,
 felhasznalo_kod integer not null,
 bejelentkezesi_ido TIMESTAMP not null ,
 FOREIGN KEY(felhasznalo_kod) REFERENCES FELHASZNALO(kod),
 primary key(kod)
);

create table OKTATO (
 tanitas_kezdete TIMESTAMP NOT NULL,
 felhasznalo_kod integer not null,
 FOREIGN KEY(felhasznalo_kod) REFERENCES FELHASZNALO(kod),
 primary key(felhasznalo_kod)
);

create table HALLGATO (
 szemeszter integer NOT NULL,
 felhasznalo_kod integer not null,
 FOREIGN KEY(felhasznalo_kod) REFERENCES FELHASZNALO(kod),
 primary key(felhasznalo_kod)
);

create table FELIRATKOZAS (
 kod integer GENERATED BY DEFAULT AS IDENTITY,
 hallgato_kod integer not null,
 kurzus_kod integer not null,
 FOREIGN KEY(hallgato_kod) REFERENCES HALLGATO(felhasznalo_kod),
 primary key(kod)
);

ALTER TABLE KURZUS
ADD CONSTRAINT fk_oktato_kod 
FOREIGN KEY (oktato_kod)
REFERENCES FELHASZNALO(kod);

ALTER TABLE KURZUS
ADD CONSTRAINT fk_terem_kod 
FOREIGN KEY (terem_kod)
REFERENCES TEREM(kod);

ALTER TABLE KURZUS
ADD CONSTRAINT fk_epulet_kod 
FOREIGN KEY (epulet_kod)
REFERENCES EPULET(kod);


create table BEJEGYZES (
 kod integer GENERATED BY DEFAULT AS IDENTITY,
 felhasznalo_kod integer not null,
 kurzus_kod integer not null,
 megiras_ideje TIMESTAMP NOT NULL,
 tartalom VARCHAR2(4000) not null,
 FOREIGN KEY(felhasznalo_kod) REFERENCES FELHASZNALO(kod),
 FOREIGN KEY(kurzus_kod) REFERENCES KURZUS(kod),
 primary key(kod)
);


ALTER TABLE FELIRATKOZAS 
ADD CONSTRAINT fk_kurzus_kod
FOREIGN KEY (kurzus_kod)
REFERENCES KURZUS(kod);


create table HIRDETMENY (
 kod integer GENERATED BY DEFAULT AS IDENTITY,
 felhasznalo_kod integer not null,
 kurzus_kod integer not null,
 megiras_ideje TIMESTAMP NOT NULL,
 tartalom VARCHAR2(4000) not null,
 FOREIGN KEY(felhasznalo_kod) REFERENCES FELHASZNALO(kod),
 FOREIGN KEY(kurzus_kod) REFERENCES KURZUS(kod),
 primary key(kod)
);

create table TANANYAG (
 kod integer GENERATED BY DEFAULT AS IDENTITY,
 nev VARCHAR(255) NOT NULL,
 kurzus_kod integer not null,
 feltoltes_datum TIMESTAMP NOT NULL,
 tananyag BLOB not null,
 FOREIGN KEY(kurzus_kod) REFERENCES KURZUS(kod),
 primary key(kod)
);


create table VIZSGA (
 kod integer GENERATED BY DEFAULT AS IDENTITY,
 idopont TIMESTAMP NOT NULL,
 kurzus_kod integer not null,
 terem_kod integer not null,
 epulet_kod integer not null,
 FOREIGN KEY(epulet_kod) REFERENCES EPULET(kod),
 FOREIGN KEY(terem_kod) REFERENCES TEREM(kod),
 FOREIGN KEY(kurzus_kod) REFERENCES KURZUS(kod),
 primary key(kod)
);




