--jo
create table EPULET (
 kod integer GENERATED BY DEFAULT AS IDENTITY,
 nev VARCHAR(255) NOT NULL,
 primary key(kod)
);

--jo
create table FELHASZNALO (
 kod integer GENERATED BY DEFAULT AS IDENTITY,
 jelszo VARCHAR(255) NOT NULL,
 keresztnev VARCHAR(255) NOT NULL,
 vezeteknev VARCHAR(255) NOT NULL,
 admin NUMBER(1) not null,
 primary key(kod)
);

--jo
create table TEREM (
 kod integer not null,
 nev VARCHAR(255),
 epulet_kod integer NOT NULL,
 FOREIGN KEY(epulet_kod) REFERENCES EPULET(kod),
 primary key(kod, epulet_kod)
);

--jo
create table LOG (
 kod integer GENERATED BY DEFAULT AS IDENTITY,
 felhasznalo_kod integer not null,
 bejelentkezesi_ido TIMESTAMP not null ,
 FOREIGN KEY(felhasznalo_kod) REFERENCES FELHASZNALO(kod),
 primary key(kod)
);

--jo
create table OKTATO (
 tanitas_kezdete TIMESTAMP NOT NULL,
 felhasznalo_kod integer not null,
 FOREIGN KEY(felhasznalo_kod) REFERENCES FELHASZNALO(kod),
 primary key(felhasznalo_kod)
);

--jo
create table HALLGATO (
 szemeszter integer NOT NULL,
 felhasznalo_kod integer not null,
 FOREIGN KEY(felhasznalo_kod) REFERENCES FELHASZNALO(kod),
 primary key(felhasznalo_kod)
);

--jo
create table KURZUS (
 kod integer GENERATED BY DEFAULT AS IDENTITY,
 nev VARCHAR(255) NOT NULL,
 max_letszam integer not null,
 oktato_kod integer,
 terem_kod integer not null,
 epulet_kod integer not null,
 FOREIGN KEY (oktato_kod) REFERENCES FELHASZNALO(kod),
 FOREIGN KEY (terem_kod, epulet_kod) REFERENCES TEREM(kod, epulet_kod),
 primary key(kod)
);

--jo
create table FELIRATKOZAS (
 kod integer GENERATED BY DEFAULT AS IDENTITY,
 hallgato_kod integer not null,
 kurzus_kod integer not null,
 FOREIGN KEY(hallgato_kod) REFERENCES HALLGATO(felhasznalo_kod),
 FOREIGN KEY (kurzus_kod) REFERENCES KURZUS(kod),
 primary key(kod)
);

--jo
create table BEJEGYZES (
 kod integer GENERATED BY DEFAULT AS IDENTITY,
 felhasznalo_kod integer not null,
 kurzus_kod integer not null,
 megiras_ideje TIMESTAMP NOT NULL,
 tartalom VARCHAR2(4000) not null,
 FOREIGN KEY(felhasznalo_kod) REFERENCES FELHASZNALO(kod),
 FOREIGN KEY(kurzus_kod) REFERENCES KURZUS(kod),
 primary key(kod)
);

--jo
create table HIRDETMENY (
 kod integer GENERATED BY DEFAULT AS IDENTITY,
 felhasznalo_kod integer not null,
 kurzus_kod integer not null,
 megiras_ideje TIMESTAMP NOT NULL,
 tartalom VARCHAR2(4000) not null,
 FOREIGN KEY(felhasznalo_kod) REFERENCES FELHASZNALO(kod),
 FOREIGN KEY(kurzus_kod) REFERENCES KURZUS(kod),
 primary key(kod)
);

--jo
create table TANANYAG (
 kod integer GENERATED BY DEFAULT AS IDENTITY,
 nev VARCHAR(255) NOT NULL,
 kurzus_kod integer not null,
 feltoltes_datum TIMESTAMP NOT NULL,
 tananyag BLOB not null,
 FOREIGN KEY(kurzus_kod) REFERENCES KURZUS(kod),
 primary key(kod)
);

--jo
create table VIZSGA (
 kod integer GENERATED BY DEFAULT AS IDENTITY,
 idopont TIMESTAMP NOT NULL,
 kurzus_kod integer not null,
 terem_kod integer not null,
 epulet_kod integer not null,
 FOREIGN KEY(terem_kod, epulet_kod) REFERENCES TEREM(kod, epulet_kod),
 FOREIGN KEY(kurzus_kod) REFERENCES KURZUS(kod),
 primary key(kod)
);


--jo
insert into epulet values ( DEFAULT,'TIK');
insert into epulet values ( DEFAULT,'IRINYI');
insert into epulet values ( DEFAULT,'BOLYAI');
insert into epulet values ( DEFAULT,'GÁBOR DÉNES ÉP.');
insert into epulet values ( DEFAULT,'CSONKA ÉP.');
insert into epulet values ( DEFAULT,'KLEBENSBERG KÖNYVTÁR');
insert into epulet values ( DEFAULT,'JÓZSEF ATTILA ÉP.');
insert into epulet values ( DEFAULT,'KLINIKÁK');
insert into epulet values ( DEFAULT,'ARANY JÁNOS ÉP.');
insert into epulet values ( DEFAULT,'BÉKE ÉP.');
insert into epulet values ( DEFAULT,'FELASZABADULÁS ÉP.');
insert into epulet values ( DEFAULT,'PRIDE ÉP.');
insert into epulet values ( DEFAULT,'REKTORI ÉP.');
